jaysBlog/config/routes.rb
JaysBlog::Application.routes.draw do

  resources :articles do
    resources :comments
  end

  resources :photos
  
  root 'welcome#index'

end

jaysBlog/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :photos

	validates :title, presence: true, uniqueness: true,
		length: {minimum: 3}
end

jaysBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

jaysBlog/app/models/photo.rb
class Photo < ActiveRecord::Base
end

jaysBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

jaysBlog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", except:
	[:index, :show]

	def new
		@article = Article.new
	end

	# def create
 	#  		render plain: params[:article].inspect
	# end

	def index
		@articles = Article.all
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])

		@article.destroy

		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

jaysBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy 
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy

		redirect_to article_path(@article)
	end

	private 
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end 


end

jaysBlog/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy 
	
	def new
		@photo = Photo.new
	end

	def index
		@photos = Photo.all
	end

	def create
		@photo = Photo.new(photo_params)

		if @photo.save
			redirect_to @photo
		else
			render 'new'
		end
	end

	def show
		@photo = Photo.find(params[:id])
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def update
		@photo = Photo.find(params[:id])

		if @photo.update(photo_params)
			redirect_to @photo
		else
			render 'edit'
		end
	end

	def destroy
		@photo = Photo.find(params[:id])

		@photo.destroy

		redirect_to photoss_path
	end

	
	private
	def photo_params
		params.require(:article).permit(:name, :url)
	end

end

jaysBlog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

jaysBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

jaysBlog/app/helpers/articles_helper.rb
module ArticlesHelper
end

jaysBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

jaysBlog/app/helpers/photos_helper.rb
module PhotosHelper
end

jaysBlog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

jaysBlog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "error")%> prohibited
				this article from being saved:
			</h2>
			<ul>
				<%@article.errors.full_messages.each do |msg|%>
					<li><%=msg%></li>
				<%end%>
			</ul>
		</div>
	<%end%>

	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p><%= f.submit%></p>
<%end%>

jaysBlog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form'%>

<%= link_to 'Back', articles_path%>

jaysBlog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New', new_article_path %>

<table>
	<tr>
		<th>Title</th><th>Text</th>
	</tr>

	<%@articles.each do |article|%>
		<tr>
			<td><%= link_to article.title, article_path(article)%>
			</td>
			<td><%= article.text%></td>
		</tr>
	<%end%>
</table>

jaysBlog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p><%= f.submit%></p>
<%end%>

<%= link_to 'Back', articles_path%>

jaysBlog/app/views/articles/show.html.erb
<%= link_to 'Edit', edit_article_path(@article)%>
<%= link_to 'Delete', article_path(@article), 
	method: :delete, 
	data: {confirm: 'Are you sure?'}%>
<p>
	<strong>Title:</strong>
	<%= @article.title%>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text%>
</p>

<h2>Comments</h2>
<%= render @article.comments%>

<h2>Add comment</h2>
<%= render "comments/form"%>

<%= link_to 'articles', articles_path%>

jaysBlog/app/views/comments/_comment.html.erb
	<p>
		<%= comment.body%><br>
		<strong>- <%= comment.commenter%></strong>
	</p>

	<p>
		<%= link_to 'Delete', [comment.article, comment],
			method: :delete,
			data: {confirm: 'Delete Comment?'}%>
	</p>

jaysBlog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f|%>
	<p>
		<%= f.label :commenter%><br>
		<%= f.text_field :commenter%>
	</p>
	<p>
		<%= f.text_area :body%>
	</p>
	<p>
		<%= f.submit%>
	</p>
<%end%>

jaysBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JaysBlog</title>
  <link href='http://fonts.googleapis.com/css?family=Habibi' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

jaysBlog/app/views/photos/_form.html.erb
<% form_for @photo do |p| %>

	<% if @photo.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@photo.errors.count, "error")%>. Photo not saved.
			</h2>
			<ul>
				<%photo.errors.full_messages.each do |msg|%>
				<li><%=msg%></li>
				<%end%>
			</ul>
		</div>
	<%end%>

	<p>
		<%= p.label :photographer%><br>
		<%= p.text_field :photographer%>
	</p>

	<p>
		<%= p.label :name%><br>
		<%= p.text_field :name%>
	</p>

	<p>
		<%= p.label :url%><br>
		<%= p.text_field :url%>
	</p>

	<p>
		<%= p.checkbox :copyrighted %>
		<%= p.label :copyrighted, "Photo is copyrighted."%>
	</p>

	<p>
		<%= p.submit "Save Photo"%>
	</p>


<%end%>

jaysBlog/app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render 'form'%>

<%= link_to 'Back to Photos', photos_path%>

jaysBlog/app/views/photos/index.html.erb
<h1>Available Photos</h1>

<%= link_to 'Add Photo', new_photo_path %>

<%@photos.each do |photo|%>
	<p>
		<%= photo.name%>, <%= "Copyright:" if photo.copyrighted%> <%= photo.photographer%>
		<%= link_to(image_tag(photo.url), photo)%>
	</p>
<%end%>

jaysBlog/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form'%>

<%= link_to 'Back to Photos', photos_path%>

jaysBlog/app/views/welcome/index.html.erb
<h1>Jay's Blog</h1>

<%= link_to 'Le Articles', controller: 'articles'%>
<%= link_to 'New article', new_article_path %>
<%= link_to 'Photos', controller: 'photos'%>
<%= link_to 'Add Photo', new_photo_path %>